name: SCRAPE_SOFIFA

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
    branches:
    - master
    - main
    - feature/setup-basic-workflow

jobs:
  scrape:
    name: Scrape Sofifa Data
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d_%H-%M-%S')"

      - name: Setup Environment
        # e.g. create work dirst, store in env variables ... https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions
        run: |
          echo "DATA_DIR=${{ github.workspace }}/data" >> $GITHUB_ENV
          echo "PLAYERS_DIR=${{ github.workspace }}/data/Players" >> $GITHUB_ENV
          echo "TEAMS_DIR=${{ github.workspace }}/data/Teams" >> $GITHUB_ENV
          echo "LEAGUES_DIR=${{ github.workspace }}/data/Leagues" >> $GITHUB_ENV

      - name: Setup Dirs
        run: |
          echo "DATA_DIR: '${DATA_DIR}'"
          echo "PLAYERS_DIR: '${PLAYERS_DIR}'"
          echo "TEAMS_DIR: '${TEAMS_DIR}'"
          echo "LEAGUES_DIR: '${LEAGUES_DIR}'"

          echo "Command: 'mkdir -p ${DATA_DIR}'"
          mkdir -p ${DATA_DIR}
          echo "Command: 'mkdir -p ${PLAYERS_DIR}'"
          mkdir -p ${PLAYERS_DIR}
          echo "Command: 'mkdir -p ${TEAMS_DIR}'"
          mkdir -p ${TEAMS_DIR}
          echo "Command: 'mkdir -p ${LEAGUES_DIR}'"
          mkdir -p ${LEAGUES_DIR}

          echo "Command: 'ls -altR ${DATA_DIR}'"
          ls -altR ${DATA_DIR}

      - name: Get Robots.txt
        run: |
          echo "Command: './scripts/handle_sofifa_robots_txt.sh "${DATA_DIR}"'"
          ./scripts/handle_sofifa_robots_txt.sh "${DATA_DIR}"

      - name: Scrape Players
        run: |
          echo "Command: './scripts/scrape_sofifa_players.sh "${PLAYERS_DIR}"'"
          ./scripts/scrape_sofifa_players.sh "${PLAYERS_DIR}"

      - name: Scrape Teams
        run: |
          echo "Command: './scripts/scrape_sofifa_teams.sh "${TEAMS_DIR}"'"
          ./scripts/scrape_sofifa_teams.sh "${TEAMS_DIR}"

      - name: Scrape Leagues
        run: |
          echo "Command: './scripts/scrape_sofifa_leagues.sh "${LEAGUES_DIR}"'"
          ./scripts/scrape_sofifa_leagues.sh "${LEAGUES_DIR}"

      - name: Zip artifact
        run: |
          zip --junk-paths -r sofifa_data ${DATA_DIR}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date.outputs.date }}
          release_name: Release ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./sofifa_data.zip
          asset_name: sofifa_data.zip
          asset_content_type: application/zip
